stages:
- lint

variables:
  IVY_LOCATION: "${CI_PROJECT_DIR}/.ivy2"
  SBT_OPTS: "-Xms512M -Xmx3G -Xss256m"

  lint:
    stage: lint
    cache:
      key: $CI_COMMIT_REF_NAME
      paths:
      - target
      - $IVY_LOCATION
      - project/project
      - project/target
      policy: pull
    tags:
    - build
    allow_failure: true
    image: hseeberger/scala-sbt:8u171_2.12.6_1.1.6
    script:
    - echo $SBT_OPTS
    - sbt -Dsbt.ivy.home=$IVY_LOCATION -Divy.home=$IVY_LOCATION scalastyle