stages:
  - build

variables:
  IVY_LOCATION: "${CI_PROJECT_DIR}/.ivy2"
  SBT_OPTS: "-Xms512M -Xmx3G -Xss256m"

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
    - ${CI_PROJECT_DIR}/target
    - ${IVY_LOCATION}
    - ${CI_PROJECT_DIR}/project/project
    - ${CI_PROJECT_DIR}/project/target
    policy: push
  tags:
    - kubernetes
  image: hseeberger/scala-sbt:8u171_2.12.6_1.1.6
  script:
    - echo ${SBT_OPTS}
    - cd dbapi/dbapi/
    - sbt -Dsbt.ivy.home=${IVY_LOCATION} -Divy.home=${IVY_LOCATION} clean assembly
    - find / -name x.jar