stages:
  - lint
  - test
  - build

variables:  
  PROJECT_DIR: "${CI_PROJECT_DIR}/dbapi/dbapi"
  SBT_OPTS: "-Dsbt.global.base=${CI_PROJECT_DIR}/sbt-cache/.sbtboot -Dsbt.boot.directory=${CI_PROJECT_DIR}/sbt-cache/.boot -Dsbt.ivy.home=${CI_PROJECT_DIR}/sbt-cache/.ivy"

lint:
  stage: lint
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
    - ${PROJECT_DIR}/target
    - ${PROJECT_DIR}/project/project
    - ${PROJECT_DIR}/project/target 
    - "${CI_PROJECT_DIR}/sbt-cache/.ivy"
    - "${CI_PROJECT_DIR}/sbt-cache/.boot"
    - "${CI_PROJECT_DIR}/sbt-cache/.sbtboot"
    - "${CI_PROJECT_DIR}/sbt-cache/target"
    policy: push
  tags:
    - kubernetes
  image: hseeberger/scala-sbt:8u181_2.12.7_1.2.6
  script:
    - cd dbapi/dbapi/
    - sbt clean scalastyle

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
    - ${PROJECT_DIR}/target
    - ${PROJECT_DIR}/project/project
    - ${PROJECT_DIR}/project/target 
    - "${CI_PROJECT_DIR}/sbt-cache/.ivy"
    - "${CI_PROJECT_DIR}/sbt-cache/.boot"
    - "${CI_PROJECT_DIR}/sbt-cache/.sbtboot"
    - "${CI_PROJECT_DIR}/sbt-cache/target"
  tags:
    - kubernetes
  image: hseeberger/scala-sbt:8u181_2.12.7_1.2.6
  script:
    - cd dbapi/dbapi/
    - sbt test   

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
    - ${PROJECT_DIR}/target
    - ${PROJECT_DIR}/project/project
    - ${PROJECT_DIR}/project/target 
    - "${CI_PROJECT_DIR}/sbt-cache/.ivy"
    - "${CI_PROJECT_DIR}/sbt-cache/.boot"
    - "${CI_PROJECT_DIR}/sbt-cache/.sbtboot"
    - "${CI_PROJECT_DIR}/sbt-cache/target"
  tags:
    - kubernetes
  image: hseeberger/scala-sbt:8u181_2.12.7_1.2.6
  script:
    - cd dbapi/dbapi/
    - sbt assembly 