stages:
  - lint
  - test
  - build

variables:  
  PROJECT_DIR: "${CI_PROJECT_DIR}/dbapi/dbapi"
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"

lint:
  stage: lint
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
    - ${PROJECT_DIR}/target
    - ${PROJECT_DIR}/project/project
    - ${PROJECT_DIR}/project/target 
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"
    policy: push
  tags:
    - kubernetes
  image: hseeberger/scala-sbt:8u181_2.12.7_1.2.6
  script:
    - cd dbapi/dbapi/
    - sbt clean scalastyle

test:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
    - ${PROJECT_DIR}/target
    - ${PROJECT_DIR}/project/project
    - ${PROJECT_DIR}/project/target 
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"
    policy: push
  tags:
    - kubernetes
  image: hseeberger/scala-sbt:8u181_2.12.7_1.2.6
  script:
    - cd dbapi/dbapi/
    - sbt test   

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
    - ${PROJECT_DIR}/target
    - ${PROJECT_DIR}/project/project
    - ${PROJECT_DIR}/project/target 
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"
    policy: push

  tags:
    - kubernetes
  image: hseeberger/scala-sbt:8u181_2.12.7_1.2.6
  script:
    - cd dbapi/dbapi/
    - sbt assembly 