apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: dbapi
  name: dbapi
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/dbapi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: dbapi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: dbapi
    spec:
      volumes:
      - name: secretvolume
        secret:
          secretName: dbconfig
      containers:
      - image: eu.gcr.io/jobsearch-225012/dbapi:latest
        imagePullPolicy: Always
        name: dbapi
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: secretvolume
          mountPath: "/etc/secretvolume"
          readOnly: true       
      dnsPolicy: ClusterFirst      
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30           
status: {}
